### ISSUE TITLE
Linux disk io stats - Unsupported item key

### ISSUE THREAD

**Issue by DeV1L** [H-Software/Zabbix-II#2]
I added this template, placed scripts to /usr/local/bin/ and added UserParameters to zabbix_agentd.conf. I linked host to this template. Now i have error "Unsupported item key" in "Discovery rules" 

![unsupported item key](https://cloud.githubusercontent.com/assets/8911626/10124729/f4f1ed34-6564-11e5-8b4d-0e1a74848756.jpg)

**Comment by czhujer** [comment]
Hi,
can you put mouse cursor on red cross? Zabbix shows more info about error.
Can you run script on server with zabbix-agent manualy?

thanks,
Patrik

**Comment by DeV1L** [comment]
I fixed it. It was my error in config file. Also needed to create regexp "Linux disks for autodiscovery"
