### ISSUE TITLE
Linux disks for autodiscovery regex

### ISSUE THREAD

**Issue by sequentiality** [H-Software/Zabbix-II#4]
Global regular expression "Linux disks for autodiscovery" does not exist.

Please, provide regex for zabbix server. Haven't found it in README.

**Comment by czhujer** [comment]
Hi,
it depends on architecture.. you can use common regular expression..

example: ^(vd[a-z]|sd[a-z]|dm-[0-9])$

![screen shot 2016-11-11 at 10 09 20](https://cloud.githubusercontent.com/assets/1621679/20209886/0295af22-a7f7-11e6-85af-e8ddc4863d85.png)
